
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=voty_db
      - FIREBASE_CONFIG_PATH=/app/firebase-auth.json
    volumes:
      # Mapea tu archivo local (en el servidor) al contenedor
      - ./cmd/server/voty.json:/app/firebase-auth.json
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=voty_db
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 5s
      retries: 10
    # Usamos mysql_native_password para asegurar compatibilidad con el driver de Go
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
